In [27]:
import import_ipynb
import Model.Location
from Model.Location import *
from Model.Enum_profile import *
from Model.Profile import *
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, HTML

'en_us'

Read Data

In [2]:
import locale
import pandas as pd
locale.setlocale(locale.LC_ALL, '')
print(locale.getdefaultlocale(['LC_ALL']))
# locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
pd.set_option('display.max_columns', 20)
pd.set_option('display.max_colwidth', 100)
pd.set_option('display.min_rows', 20)
pd.options.display.min_rows = 30
pd.options.display.max_rows = 30
data = pd.read_csv('./Exple.csv', sep = ";", parse_dates=['Date'])
index = pd.date_range(start='1/1/2020', periods=8784, freq = '1h00t')
data['time'] = index
data.set_index('time', inplace = True)
data['FDate'] = pd.to_datetime(data['Date']) 
data['day_of_week'] = data['FDate'].dt.day_name()

data.drop(['Date','Heures'], axis = 1,inplace = True)

('en_US', 'UTF-8')

In [58]:
week_df = data.groupby(data['FDate'].dt.day_name()).mean()
display (week_df)

,Conso_stade,Conso_scolaire,Conso_inactif,Conso_Actif,Solaire
FDate,,,,,
Friday,0.381003,5.500561,1.439183,1.637300,1379.661098
Monday,0.378180,5.613702,1.297115,1.636987,1316.517134
Saturday,0.388180,2.903462,1.725761,1.609022,1394.251939
Sunday,0.385071,3.254984,1.579728,1.823486,1470.359912
Thursday,0.380378,5.877241,1.256887,1.550629,1362.154741
Tuesday,0.380096,5.402388,1.312404,1.567708,1380.140208
Wednesday,0.380208,5.390920,1.313734,1.522980,1339.183404

In [59]:

with pd.option_context('display.min_rows', 30,'display.max_rows', 30, 'display.max_columns', 20):
    display(data)

,Conso_stade,Conso_scolaire,Conso_inactif,Conso_Actif,Solaire,FDate,day_of_week
time,,,,,,,
2020-01-01 00:00:00,0.5610,2.64,0.86,0.86,0.00,2020-01-01,Wednesday
2020-01-01 01:00:00,0.4950,2.25,0.73,0.73,0.00,2020-01-01,Wednesday
2020-01-01 02:00:00,0.2970,1.95,0.60,0.90,0.00,2020-01-01,Wednesday
2020-01-01 03:00:00,0.2970,1.98,0.60,0.90,0.00,2020-01-01,Wednesday
2020-01-01 04:00:00,0.2970,1.80,0.60,0.90,0.00,2020-01-01,Wednesday
2020-01-01 05:00:00,0.3960,2.10,1.00,1.50,0.00,2020-01-01,Wednesday
2020-01-01 06:00:00,0.3630,3.90,1.80,2.70,0.00,2020-01-01,Wednesday
2020-01-01 07:00:00,0.2970,5.10,1.90,2.90,175.00,2020-01-01,Wednesday
2020-01-01 08:00:00,0.2970,9.30,1.60,2.40,640.00,2020-01-01,Wednesday
2020-01-01 09:00:00,0.2805,10.80,1.20,1.80,1464.00,2020-01-01,Wednesday
2020-01-01 10:00:00,0.2640,12.00,0.53,0.90,2100.00,2020-01-01,Wednesday
2020-01-01 11:00:00,0.2640,12.60,0.54,0.80,2426.00,2020-01-01,Wednesday
2020-01-01 12:00:00,0.2640,11.10,0.53,0.95,2354.00,2020-01-01,Wednesday
2020-01-01 13:00:00,0.2640,6.60,0.53,1.10,1875.00,2020-01-01,Wednesday
2020-01-01 14:00:00,0.2640,11.70,0.53,1.05,1038.00,2020-01-01,Wednesday
...,...,...,...,...,...,...,...
2020-12-31 09:00:00,0.2805,1.92,1.20,1.80,793.00,2020-12-31,Thursday
2020-12-31 10:00:00,0.2310,1.80,0.51,0.90,2074.00,2020-12-31,Thursday
2020-12-31 11:00:00,0.2475,2.00,0.53,0.85,3201.00,2020-12-31,Thursday
2020-12-31 12:00:00,0.2970,2.20,0.49,1.00,3798.00,2020-12-31,Thursday
2020-12-31 13:00:00,0.2805,1.20,0.53,1.05,3801.00,2020-12-31,Thursday
2020-12-31 14:00:00,0.2541,1.95,0.54,0.78,3099.00,2020-12-31,Thursday
2020-12-31 15:00:00,0.2904,1.83,0.53,0.92,1975.53,2020-12-31,Thursday
2020-12-31 16:00:00,0.3102,1.80,0.53,0.99,709.00,2020-12-31,Thursday
2020-12-31 17:00:00,0.5280,2.10,1.20,1.20,158.46,2020-12-31,Thursday
2020-12-31 18:00:00,0.6270,2.70,2.53,2.53,0.00,2020-12-31,Thursday
2020-12-31 19:00:00,0.6600,1.15,2.26,2.26,0.00,2020-12-31,Thursday
2020-12-31 20:00:00,0.6270,1.95,1.40,1.40,0.00,2020-12-31,Thursday
2020-12-31 21:00:00,0.5970,0.49,1.86,1.86,0.00,2020-12-31,Thursday
2020-12-31 22:00:00,0.5610,1.80,1.27,1.26,0.00,2020-12-31,Thursday
2020-12-31 23:00:00,0.5280,1.60,1.20,1.20,0.00,2020-12-31,Thursday

In [17]:
# Solar park installed in 2020 = 10020
data['Solaire_kwh']= data['Solaire']/10020
data

,Conso_stade,Conso_scolaire,Conso_inactif,Conso_Actif,Solaire,Solaire_kwh
time,,,,,,
2020-01-01 00:00:00,0.561,2.64,0.86,0.86,0.0,0.0
2020-01-01 01:00:00,0.495,2.25,0.73,0.73,0.0,0.0
2020-01-01 02:00:00,0.297,1.95,0.60,0.90,0.0,0.0
2020-01-01 03:00:00,0.297,1.98,0.60,0.90,0.0,0.0
2020-01-01 04:00:00,0.297,1.80,0.60,0.90,0.0,0.0
...,...,...,...,...,...,...
2020-12-31 19:00:00,0.660,1.15,2.26,2.26,0.0,0.0
2020-12-31 20:00:00,0.627,1.95,1.40,1.40,0.0,0.0
2020-12-31 21:00:00,0.597,0.49,1.86,1.86,0.0,0.0
2020-12-31 22:00:00,0.561,1.80,1.27,1.26,0.0,0.0
2020-12-31 23:00:00,0.528,1.60,1.20,1.20,0.0,0.0

In [1]:
data['production'] = data['Solaire_kwh'] * 2.5

NameError: name 'data' is not defined